/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface;

import ArayuzIslemleri.GirişEkranIslemleri;
import ArayuzIslemleri.RenkVeIconlar;
import SQLIslemleri.SQLKullanıcıIslemleri;
import Users.User;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.Objects;
import java.util.concurrent.Future;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author MONSTER
 */
public class Login extends javax.swing.JFrame {
    //Değişkenler-DB
    private String DB_KULLANICI="kullanıcılar";
    
    //Classlar
    SQLKullanıcıIslemleri sqlKullanıcı=new SQLKullanıcıIslemleri(DB_KULLANICI);
    RenkVeIconlar renkveIconlar = new RenkVeIconlar();
    Dimension dim= Toolkit.getDefaultToolkit().getScreenSize();
    GirişEkranIslemleri girisEkranı;
    
    //Değişkenler
    public Integer posX;//Mouse konum değerleri
    public Integer posY ;
    
    //Değişkenler Sonradan Silinecekler
    public String KullanıcıAdı="Tuna";
    public String Şifre="12345";
    private boolean sifreKurtarmaIslemi;
    
    
    
    public Login() {
        initComponents();
        initComponents_2(false);
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    public void initComponents_2(boolean açılış){
       
           
        jTextField_KullanıcıAdı.setVisible(!açılış);
        jPasswordField_Password.setVisible(!açılış); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_GirişIcon = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_GirişParametre = new javax.swing.JPanel();
        jPanel_Navigasyon = new javax.swing.JPanel();
        jLabel_Close = new javax.swing.JLabel();
        jLabel_Minimaze = new javax.swing.JLabel();
        jLabel_Move = new javax.swing.JLabel();
        jPanel_Kullanıcıİcon = new javax.swing.JPanel();
        jLabel_UserIcon = new javax.swing.JLabel();
        jTextField_KullanıcıAdı = new javax.swing.JTextField();
        jPasswordField_Password = new javax.swing.JPasswordField();
        jButton_GirişYap = new javax.swing.JButton();
        jButton_Register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel_GirişIcon.setBackground(new java.awt.Color(0, 204, 204));
        jPanel_GirişIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chat (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel_GirişIconLayout = new javax.swing.GroupLayout(jPanel_GirişIcon);
        jPanel_GirişIcon.setLayout(jPanel_GirişIconLayout);
        jPanel_GirişIconLayout.setHorizontalGroup(
            jPanel_GirişIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );
        jPanel_GirişIconLayout.setVerticalGroup(
            jPanel_GirişIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel_GirişParametre.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_GirişParametre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel_Navigasyon.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png"))); // NOI18N
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseExited(evt);
            }
        });

        jLabel_Minimaze.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jLabel_Minimaze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MinimazeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MinimazeMouseEntered(evt);
            }
        });

        jLabel_Move.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Move.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Move.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/four-arrows.png"))); // NOI18N
        jLabel_Move.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel_MoveMouseDragged(evt);
            }
        });
        jLabel_Move.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_MoveMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_NavigasyonLayout = new javax.swing.GroupLayout(jPanel_Navigasyon);
        jPanel_Navigasyon.setLayout(jPanel_NavigasyonLayout);
        jPanel_NavigasyonLayout.setHorizontalGroup(
            jPanel_NavigasyonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NavigasyonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Move, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Minimaze, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Close))
        );
        jPanel_NavigasyonLayout.setVerticalGroup(
            jPanel_NavigasyonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_NavigasyonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Minimaze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel_Move, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel_Kullanıcıİcon.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_UserIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_KullanıcıİconLayout = new javax.swing.GroupLayout(jPanel_Kullanıcıİcon);
        jPanel_Kullanıcıİcon.setLayout(jPanel_KullanıcıİconLayout);
        jPanel_KullanıcıİconLayout.setHorizontalGroup(
            jPanel_KullanıcıİconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_UserIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_KullanıcıİconLayout.setVerticalGroup(
            jPanel_KullanıcıİconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_KullanıcıİconLayout.createSequentialGroup()
                .addComponent(jLabel_UserIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        jTextField_KullanıcıAdı.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        jTextField_KullanıcıAdı.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Kullanıcı Adı", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Agency FB", 1, 18))); // NOI18N
        jTextField_KullanıcıAdı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_KullanıcıAdıActionPerformed(evt);
            }
        });
        jTextField_KullanıcıAdı.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_KullanıcıAdıKeyPressed(evt);
            }
        });

        jPasswordField_Password.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18))); // NOI18N
        jPasswordField_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_PasswordActionPerformed(evt);
            }
        });
        jPasswordField_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_PasswordKeyPressed(evt);
            }
        });

        jButton_GirişYap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/enter.png"))); // NOI18N
        jButton_GirişYap.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Login"));
        jButton_GirişYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GirişYapActionPerformed(evt);
            }
        });

        jButton_Register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/register (1).png"))); // NOI18N
        jButton_Register.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Register"));
        jButton_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_GirişParametreLayout = new javax.swing.GroupLayout(jPanel_GirişParametre);
        jPanel_GirişParametre.setLayout(jPanel_GirişParametreLayout);
        jPanel_GirişParametreLayout.setHorizontalGroup(
            jPanel_GirişParametreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Navigasyon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Kullanıcıİcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_GirişParametreLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_GirişParametreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPasswordField_Password)
                    .addGroup(jPanel_GirişParametreLayout.createSequentialGroup()
                        .addComponent(jTextField_KullanıcıAdı, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_GirişParametreLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton_GirişYap, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addGap(20, 20, 20))
        );
        jPanel_GirişParametreLayout.setVerticalGroup(
            jPanel_GirişParametreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_GirişParametreLayout.createSequentialGroup()
                .addComponent(jPanel_Navigasyon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_Kullanıcıİcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jTextField_KullanıcıAdı, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_GirişParametreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_GirişYap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_GirişIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_GirişParametre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_GirişIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_GirişParametre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_KullanıcıAdıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_KullanıcıAdıActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_KullanıcıAdıActionPerformed

    private void jPasswordField_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_PasswordActionPerformed

    private void jLabel_MinimazeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimazeMouseEntered
      
    }//GEN-LAST:event_jLabel_MinimazeMouseEntered

    private void jLabel_CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseExited
       
    }//GEN-LAST:event_jLabel_CloseMouseExited

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    private void jLabel_MinimazeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MinimazeMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel_MinimazeMouseClicked

    private void jLabel_MoveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MoveMousePressed
        posX= evt.getX();
        posY=evt.getY();
    }//GEN-LAST:event_jLabel_MoveMousePressed

    private void jLabel_MoveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MoveMouseDragged
        this.setLocation(evt.getXOnScreen()- posX-461, evt.getYOnScreen()- posY);
    }//GEN-LAST:event_jLabel_MoveMouseDragged

    private void jButton_GirişYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GirişYapActionPerformed
       
girisEkranı=new GirişEkranIslemleri(jTextField_KullanıcıAdı, jPasswordField_Password);
   
  String girilenKullanıcıAdı =jTextField_KullanıcıAdı.getText();
  String girilenKullanıcıSifre= new String(jPasswordField_Password.getPassword());
  boolean girisSonuc=false;
  boolean sifreSonuc=false;
 User user;


// Kullanıcı adı ve şifrenin doğruluğunu kontrol etmek için bir boolean tanımla
boolean girisBasarili = false;

try {
    // Giriş ekranı işlemlerini gerçekleştir
    girisBasarili = girisEkranı.boşGirisKontrol();   
    if (girisBasarili) {
        // Kullanıcı adı ve şifreyi veritabanında kontrol et
        user = sqlKullanıcı.kullanıcıBul(girilenKullanıcıAdı, girilenKullanıcıSifre);
        if (user != null) {
            // Giriş başarılıysa ana pencereyi aç
            this.setVisible(false);
            MAINUI mainUI = new MAINUI(user);
            mainUI.setVisible(true);
        } else {
            // Kullanıcı adı veya şifre yanlışsa hata mesajı göster
            JOptionPane.showMessageDialog(this, "Hatalı Kullanıcı Adı ya da Şifresi Girdiniz");
        }
    } else {
        // Giriş bilgileri eksikse hata mesajı göster
        JOptionPane.showMessageDialog(this, girisEkranı.getSonucMesaj());
    }
        }catch (SQLException ex) {
           Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Hatalı Kullanıcı Adı ya da Şifresi Girdiniz");
               }

       
       
       
       
       /*String girilenKullanıcıAdı=jTextField_KullanıcıAdı.getText();
       String girilenPassword= new String(jPasswordField_Password.getPassword());
       
       if(girilenKullanıcıAdı.equals("") && girilenPassword.equals("")){
          JOptionPane.showMessageDialog(this,"Kullanıcı Adı veya Şifre Girmediniz");
       }else{
           if(girilenKullanıcıAdı.equals(KullanıcıAdı)&& Objects.equals(girilenPassword,Şifre)){
            System.out.println("Hoşgeldiniz");
           }else{
               JOptionPane.showMessageDialog(this,"Kullanıcı Adı veya Şifreniz Yanlış");
           }
       }*/
    }//GEN-LAST:event_jButton_GirişYapActionPerformed

    private void jTextField_KullanıcıAdıKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_KullanıcıAdıKeyPressed
        if(evt.getKeyChar()==KeyEvent.VK_ENTER){
        jButton_GirişYap.doClick();
        }
    }//GEN-LAST:event_jTextField_KullanıcıAdıKeyPressed

    private void jPasswordField_PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordKeyPressed
        if(evt.getKeyChar()==KeyEvent.VK_ENTER){
        jButton_GirişYap.doClick();
        }
    }//GEN-LAST:event_jPasswordField_PasswordKeyPressed

    private void jButton_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegisterActionPerformed
        Register registerFrame = new Register(); // RegisterJFrame'inizin ismini ve oluşturma kodunu uygun şekilde değiştirin
        registerFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_RegisterActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_GirişYap;
    private javax.swing.JButton jButton_Register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_Minimaze;
    private javax.swing.JLabel jLabel_Move;
    private javax.swing.JLabel jLabel_UserIcon;
    private javax.swing.JPanel jPanel_GirişIcon;
    private javax.swing.JPanel jPanel_GirişParametre;
    private javax.swing.JPanel jPanel_Kullanıcıİcon;
    private javax.swing.JPanel jPanel_Navigasyon;
    private javax.swing.JPasswordField jPasswordField_Password;
    private javax.swing.JTextField jTextField_KullanıcıAdı;
    // End of variables declaration//GEN-END:variables
}
