/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface;

import Users.User;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author MONSTER
 */
public class MAINUI extends javax.swing.JFrame {

    /**
     * Creates new form MAINUI
     */
    public MAINUI() {
        initComponents();
       jPanel_Profile.setVisible(true);
       jPanel_Group.setVisible(false);
       jPanel_Friends.setVisible(false);
        
    }
    public MAINUI(User user) {
        initComponents();
        System.out.println("Hoşgeldiniz:"+user.getName());
    }
    private JLabel createMessageLabel(String message) {
    JLabel label = new JLabel(message);
    label.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    label.setMaximumSize(new Dimension(380, Integer.MAX_VALUE));
    label.setAlignmentX(Component.LEFT_ALIGNMENT);
    return label;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_AnaPanel = new javax.swing.JPanel();
        jPanel_Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton_LogOut = new javax.swing.JButton();
        jToggleButton_Profile = new javax.swing.JToggleButton();
        jToggleButton_Friends = new javax.swing.JToggleButton();
        jToggleButton_Groups = new javax.swing.JToggleButton();
        jPanel_GenelPanel = new javax.swing.JPanel();
        jPanel_Group = new javax.swing.JPanel();
        jPanel_Friends = new javax.swing.JPanel();
        jPanel_Profile = new javax.swing.JPanel();
        jLabel_Foto = new javax.swing.JLabel();
        jLabel_KullanıcıAdı = new javax.swing.JLabel();
        jTextField_Post = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_Header.setBackground(new java.awt.Color(204, 255, 204));
        jPanel_Header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ux (1).png"))); // NOI18N

        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel_HeaderLayout = new javax.swing.GroupLayout(jPanel_Header);
        jPanel_Header.setLayout(jPanel_HeaderLayout);
        jPanel_HeaderLayout.setHorizontalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_HeaderLayout.setVerticalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jButton_LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/log-out.png"))); // NOI18N
        jButton_LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_LogOutMouseClicked(evt);
            }
        });
        jButton_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LogOutActionPerformed(evt);
            }
        });

        jToggleButton_Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user (2).png"))); // NOI18N
        jToggleButton_Profile.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18))); // NOI18N
        jToggleButton_Profile.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton_ProfileİtemStateChanged(evt);
            }
        });
        jToggleButton_Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_ProfileActionPerformed(evt);
            }
        });

        jToggleButton_Friends.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/friends.png"))); // NOI18N
        jToggleButton_Friends.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Friends", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18))); // NOI18N
        jToggleButton_Friends.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton_FriendsİtemStateChanged(evt);
            }
        });
        jToggleButton_Friends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_FriendsActionPerformed(evt);
            }
        });

        jToggleButton_Groups.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/group.png"))); // NOI18N
        jToggleButton_Groups.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Groups", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18))); // NOI18N
        jToggleButton_Groups.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButton_GroupsİtemStateChanged(evt);
            }
        });
        jToggleButton_Groups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_GroupsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButton_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addComponent(jToggleButton_Profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToggleButton_Groups, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToggleButton_Friends, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jToggleButton_Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jToggleButton_Friends, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jToggleButton_Groups, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel_GenelPanel.setBackground(new java.awt.Color(0, 153, 153));
        jPanel_GenelPanel.setLayout(new java.awt.CardLayout());

        jPanel_Group.setBackground(new java.awt.Color(255, 255, 102));

        javax.swing.GroupLayout jPanel_GroupLayout = new javax.swing.GroupLayout(jPanel_Group);
        jPanel_Group.setLayout(jPanel_GroupLayout);
        jPanel_GroupLayout.setHorizontalGroup(
            jPanel_GroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
        );
        jPanel_GroupLayout.setVerticalGroup(
            jPanel_GroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );

        jPanel_GenelPanel.add(jPanel_Group, "card3");

        javax.swing.GroupLayout jPanel_FriendsLayout = new javax.swing.GroupLayout(jPanel_Friends);
        jPanel_Friends.setLayout(jPanel_FriendsLayout);
        jPanel_FriendsLayout.setHorizontalGroup(
            jPanel_FriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
        );
        jPanel_FriendsLayout.setVerticalGroup(
            jPanel_FriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );

        jPanel_GenelPanel.add(jPanel_Friends, "card4");

        jPanel_Profile.setBackground(new java.awt.Color(51, 255, 51));

        jLabel_Foto.setText("jLabel2");

        jLabel_KullanıcıAdı.setText("jLabel3");

        jTextField_Post.setText("jTextField2");

        jButton1.setText("Gönder");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ProfileLayout = new javax.swing.GroupLayout(jPanel_Profile);
        jPanel_Profile.setLayout(jPanel_ProfileLayout);
        jPanel_ProfileLayout.setHorizontalGroup(
            jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ProfileLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_KullanıcıAdı, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Post, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_ProfileLayout.setVerticalGroup(
            jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_KullanıcıAdı, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_Post)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addContainerGap(716, Short.MAX_VALUE))
        );

        jPanel_GenelPanel.add(jPanel_Profile, "card4");

        javax.swing.GroupLayout jPanel_AnaPanelLayout = new javax.swing.GroupLayout(jPanel_AnaPanel);
        jPanel_AnaPanel.setLayout(jPanel_AnaPanelLayout);
        jPanel_AnaPanelLayout.setHorizontalGroup(
            jPanel_AnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_AnaPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_GenelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_AnaPanelLayout.setVerticalGroup(
            jPanel_AnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AnaPanelLayout.createSequentialGroup()
                .addComponent(jPanel_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel_AnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_GenelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_AnaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_AnaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_LogOutActionPerformed

    private void jToggleButton_ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_ProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton_ProfileActionPerformed

    private void jToggleButton_FriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_FriendsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton_FriendsActionPerformed

    private void jToggleButton_GroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_GroupsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton_GroupsActionPerformed

    private void jToggleButton_ProfileİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jToggleButton_ProfileİtemStateChanged
       jPanel_Profile.setVisible(true);
       jPanel_Group.setVisible(false);
       jPanel_Friends.setVisible(false);
    }//GEN-LAST:event_jToggleButton_ProfileİtemStateChanged

    private void jToggleButton_FriendsİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jToggleButton_FriendsİtemStateChanged
       jPanel_Profile.setVisible(false);
       jPanel_Group.setVisible(false);
       jPanel_Friends.setVisible(true);
    }//GEN-LAST:event_jToggleButton_FriendsİtemStateChanged

    private void jToggleButton_GroupsİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jToggleButton_GroupsİtemStateChanged
       jPanel_Profile.setVisible(false);
       jPanel_Group.setVisible(true);
       jPanel_Friends.setVisible(false);
    }//GEN-LAST:event_jToggleButton_GroupsİtemStateChanged

    private void jButton_LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_LogOutMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton_LogOutMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           String message = jTextField_Post.getText();
    
    // Check if the message is not empty
    if (!message.isEmpty()) {
        // Create a new JTextArea for the new profile panel
        JTextArea newTextArea = new JTextArea();
        newTextArea.setText(message);
        newTextArea.setEditable(false); // Disable editing
        
        // Create a new JScrollPane for the JTextArea
        JScrollPane scrollPane = new JScrollPane(newTextArea);
        
        // Set the bounds for the JScrollPane
        scrollPane.setBounds(0,jPanel_Profile.getComponentCount() * 100, 400, 80);
        
        // Add the scroll pane to the jPanel_Profile
        jPanel_Profile.add(scrollPane);
        
        // Refresh jPanel_Profile to reflect the changes
        jPanel_Profile.revalidate();
        jPanel_Profile.repaint();
        
        // Clear the jTextField2
        jTextField_Post.setText("");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAINUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAINUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAINUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAINUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAINUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_LogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Foto;
    private javax.swing.JLabel jLabel_KullanıcıAdı;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_AnaPanel;
    private javax.swing.JPanel jPanel_Friends;
    private javax.swing.JPanel jPanel_GenelPanel;
    private javax.swing.JPanel jPanel_Group;
    private javax.swing.JPanel jPanel_Header;
    private javax.swing.JPanel jPanel_Profile;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_Post;
    private javax.swing.JToggleButton jToggleButton_Friends;
    private javax.swing.JToggleButton jToggleButton_Groups;
    private javax.swing.JToggleButton jToggleButton_Profile;
    // End of variables declaration//GEN-END:variables
}
